"""ChatFlow and ChatFlowNode — the outer conversation graph."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator

from agentloom.schemas.common import (
    EditableText,
    ExecutionMode,
    NodeBase,
    NodeHasReferencesError,
    NodeId,
    NodeStatus,
    ProviderModelRef,
    StickyNote,
    generate_node_id,
    utcnow,
)
from agentloom.schemas.workflow import CompactSnapshot, WorkFlow


#: Canned greeting written to a brand-new ChatFlow's root node. Static
#: for MVP; once root-behaviors land, this will be replaced by a mini
#: workflow the chat designer can edit (prompts, tools, etc.).
DEFAULT_GREETING = "Hi! I'm your assistant. Ask me anything."


PendingTurnSource = Literal["web", "discord", "feishu", "api", "test"]

#: What to do with a queued turn whose upstream node just failed.
#:
#: - ``discard`` (default): drop the turn, notify the channel. Used by
#:   every channel in Round A — failures are treated as conversation
#:   breakers, not transient glitches.
#: - ``continue``: ignore the upstream failure and try to run anyway.
#:   Reserved for future channels that want at-least-once semantics
#:   (e.g. a batch-ingest channel that retries each turn independently).
#:   The engine does *not* honor ``continue`` yet — the field is stored
#:   so the policy travels with the turn and the call-site decision
#:   stays in one place once the feature lands.
UpstreamFailurePolicy = Literal["discard", "continue"]

#: How a compact decides which trailing messages to keep verbatim.
#:
#: - ``by_count``: preserve exactly the last ``compact_keep_recent_count``
#:   messages; ``compact_target_pct`` / ``chatnode_compact_target_pct`` are
#:   ignored on the preserve side (summary is also left uncapped in this mode).
#: - ``by_budget``: greedy-pack tail messages into the leftover of
#:   ``target_pct × context_window − tiktoken(summary)``; the fixed N knob
#:   stops applying.
#:
#: Applies to both compact tiers (ChatFlow-layer and WorkFlow-layer).
CompactPreserveMode = Literal["by_count", "by_budget"]


class PendingTurn(BaseModel):
    """A queued-but-not-yet-executed user turn attached to a ChatFlowNode.

    Lives on ``ChatFlowNode.pending_queue`` — see ADR-009 addendum: the
    pending_queue is ancillary state, not part of the node's frozen
    dialogue payload, so it can be mutated on a frozen node.

    The queue "walks" down the chain as each node transitions to
    succeeded: the head item becomes the user_message of a newly-created
    child, and the remaining tail is transferred to that child's own
    pending_queue. Whichever node currently holds the queue is the
    "live tip" of its chain.

    ``source`` captures which channel submitted the turn so the
    scheduler can apply channel-specific failure policies (e.g. discard
    vs. continue on upstream failure). ``source_metadata`` carries
    per-channel meta such as discord user id / thread id — opaque to
    the engine.
    """

    id: NodeId = Field(default_factory=generate_node_id)
    text: str
    source: PendingTurnSource = "web"
    source_metadata: dict[str, Any] = Field(default_factory=dict)
    on_upstream_failure: UpstreamFailurePolicy = "discard"
    created_at: datetime = Field(default_factory=utcnow)
    #: Model the user picked in the composer when this turn was queued.
    #: ``None`` → the child inherits from its primary parent's
    #: ``resolved_model``. Travels with the PendingTurn so a queued turn
    #: keeps its model choice even as the tip advances down the chain.
    spawn_model: ProviderModelRef | None = None
    #: Per-kind composer overrides for this turn. ``None`` falls back
    #: through chatflow.default_judge_model / default_tool_call_model
    #: → spawn_model → draft_model. Lets the user route a single turn's
    #: judges/tool-call follow-ups to a different model than the main
    #: turn without touching ChatFlow defaults.
    judge_spawn_model: ProviderModelRef | None = None
    tool_call_spawn_model: ProviderModelRef | None = None


class ChatFlowNode(NodeBase):
    """One user-turn + agent-turn pair, or the greeting root.

    Two shapes exist:
    - **Turn node**: ``user_message`` is set; ``agent_response`` is set
      once the inner workflow has run; ``workflow`` is the inner DAG
      that produced the response.
    - **Greeting root**: ``user_message`` is ``None``; ``agent_response``
      carries an opening line from the chat designer (static for MVP,
      will become a mini-workflow once root-behaviors land).

    Merge nodes have ``parent_ids`` with ≥2 entries; the ``user_message``
    is auto-generated by the ``merge`` system workflow in that case.

    ``pending_queue`` holds turns the user has submitted but that
    haven't begun executing yet — see :class:`PendingTurn`. It is the
    only field on a frozen node the repository layer allows to change.
    """

    user_message: EditableText | None = None
    agent_response: EditableText = Field(default_factory=EditableText)
    workflow: WorkFlow = Field(default_factory=WorkFlow)
    pending_queue: list[PendingTurn] = Field(default_factory=list)
    #: Tier 2 compact marker. When non-``None`` this ChatNode IS the
    #: compaction point for its subtree: ``agent_response.text`` holds
    #: the summary prose, ``compact_snapshot.preserved_messages`` is the
    #: tail that wasn't summarized, and downstream context builds
    #: skip every ancestor above this node — see
    #: :func:`agentloom.engine.chatflow_engine._build_chat_context`.
    #: ``user_message`` may still carry the user's compact instruction
    #: when the compaction was explicit; engine-triggered compacts
    #: leave it ``None``.
    compact_snapshot: CompactSnapshot | None = None
    #: Forget-counter state for pre-compact ChatNodes the agent has
    #: pulled back via ``get_node_context``. Keys are source ChatNode
    #: ids; values are the remaining counter (n = memory capacity,
    #: decremented once per turn the source isn't re-fetched, dropped
    #: when it hits 0). Inherited from the primary parent at spawn time
    #: — fork siblings therefore evolve their sticky state independently,
    #: and a merge ChatNode takes MAX over both sources (so content that
    #: was fresh on either branch survives the merge). Empty on greeting
    #: roots and on nodes that never invoked ``get_node_context`` below
    #: an active compact ancestor.
    sticky_restored: dict[str, int] = Field(default_factory=dict)
    #: Estimated tokens in the chain context this ChatNode was spawned
    #: with — i.e. ``_build_chat_context`` output at creation time,
    #: including this node's own user turn (if any). The engine stamps
    #: it once at spawn; it never changes afterward. The canvas TokenBar
    #: reads this to show monotonic context growth along the chain
    #: instead of heuristically inferring incoming/outgoing from the
    #: inner WorkFlow's first/last WorkNode — that heuristic became
    #: unreliable once WorkFlows grew sub-delegations and multi-round
    #: judge iterations. ``None`` on legacy nodes predating this field;
    #: UI falls back to the old heuristic in that case.
    entry_prompt_tokens: int | None = None
    #: Estimated tokens in this ChatNode's ``agent_response.text`` — the
    #: assistant turn that ``_build_chat_context`` will emit for every
    #: descendant. Stamped once when the turn finalises (after
    #: ``agent_response`` is written) and stays put. The canvas adds
    #: this to ``entry_prompt_tokens`` so the card shows what the *next*
    #: turn's first WorkNode will consume as input, not what *this*
    #: turn consumed. ``None`` while the turn is still running and on
    #: legacy nodes predating the field.
    output_response_tokens: int | None = None


class ChatFlow(BaseModel):
    id: NodeId = Field(default_factory=generate_node_id)
    title: str | None = None
    description: str | None = None
    tags: list[str] = Field(default_factory=list)
    nodes: dict[NodeId, ChatFlowNode] = Field(default_factory=dict)
    root_ids: list[NodeId] = Field(default_factory=list)
    #: Main turn model — used for every ``StepKind.DRAFT``
    #: WorkNode in this chatflow unless a node's own ``model_override``
    #: wins. Renamed from ``default_model`` in the MemoryBoard PR
    #: (2026-04-20); alembic migration 0012 rewrites the JSONB key
    #: inside persisted chatflow payloads, and ``_legacy_default_model``
    #: below lets in-flight JSON deserialization accept either name.
    draft_model: ProviderModelRef | None = None
    #: Per-call-type overrides of ``draft_model``. When set, judge
    #: calls (pre/during/post) use ``default_judge_model``; tool-call
    #: follow-up LLM calls use ``default_tool_call_model``. Falls back
    #: to ``draft_model`` when ``None``. Lets a chatflow run a cheap
    #: model for verification/tool-routing while keeping a strong model
    #: for the main LLM step.
    default_judge_model: ProviderModelRef | None = None
    default_tool_call_model: ProviderModelRef | None = None
    #: Optional pin for ``StepKind.BRIEF`` WorkNodes (MemoryBoard
    #: producer — see design doc 2026-04-20). When set, every brief
    #: call in this chatflow's WorkFlows runs on this model regardless
    #: of the main turn model. ``None`` → brief runs fall back to the
    #: per-WorkNode ``model_override`` → source node's resolved_model.
    #: Invariant (enforced below): the brief_model's context_window
    #: must be at least as large as draft_model's, so a flow-brief
    #: summarizing a long draft context never silently truncates.
    brief_model: ProviderModelRef | None = None
    #: ReAct inner-loop cap shared by every WorkFlow in this ChatFlow.
    #: ``None`` means unlimited. Per-WorkFlow and per-WorkNode overrides
    #: are planned. See §5.4 FR-EX-6.
    tool_loop_budget: int | None = 12
    #: Auto-mode halt cap: total ``judge_during.verdict == "revise"`` tolerated
    #: per WorkFlow run before the engine pauses at ``waiting_for_user``.
    #: Per-WorkNode override allowed; ``None`` = unlimited. See §5.3 FR-PL-7.
    auto_mode_revise_budget: int | None = 3
    #: Hard cap on planner↔planner_judge / worker↔worker_judge debate
    #: rounds before the engine forces convergence (routes through
    #: judge_post). Applied to every new turn's inner WorkFlow. See §3.4.5.
    debate_round_budget: int = 3
    #: Hard cap on judge_post retry rounds. When a judge_post returns
    #: ``verdict=retry`` with ``redo_targets``, the engine re-spawns
    #: those subtasks and re-aggregates — up to this many rounds total
    #: (round 1 is the initial judgement). ``-1`` = unlimited. Applied
    #: to every new turn's inner WorkFlow.
    judge_retry_budget: int = 3
    #: Ground-ratio fuse — halts a WorkFlow (or sub_agent_delegation)
    #: whose planner is spinning without ever reaching a real tool_call.
    #: ``min_ground_ratio`` is the minimum fraction of completed leaf
    #: nodes (llm_call + tool_call + judge_call, excluding
    #: sub_agent_delegation containers) that must be ``tool_call`` before
    #: the engine halts the layer. ``None`` disables the check entirely.
    #: ``ground_ratio_grace_nodes`` is the number of completed leaves
    #: required before the fuse arms — keeps a healthy run's first few
    #: planner/judge steps from tripping it. Each recursive engine level
    #: evaluates its own local ratio independently; overall runaway is
    #: still bounded because every level applies the fuse. See §5.4
    #: (planner-grounding fuse).
    min_ground_ratio: float | None = 0.05
    ground_ratio_grace_nodes: int = 20
    #: Per-ChatFlow tool denylist. Tool names listed here are hidden
    #: from every LLM call inside this chatflow's WorkFlows AND refused
    #: at execute-time if the model hallucinates them. Covers both
    #: built-in tools (``Bash``, ``Read``, etc.) and MCP tools
    #: (``mcp__<server>__<tool>``). An empty list means "no extra
    #: filter" — every globally-registered tool is visible.
    #:
    #: New chatflows pre-populate this from the workspace tool settings
    #: (every tool whose global state is ``available`` lands in here so
    #: it stays unchecked by default; ``default_allow`` tools are NOT
    #: pre-listed and remain checked). See M7.5 step 2/3.
    disabled_tool_names: list[str] = Field(default_factory=list)
    #: Execution mode applied to every new turn's inner WorkFlow. The
    #: ChatFlowEngine derives the four switch defaults (``plan_enabled``,
    #: ``judge_pre_enabled``, ``judge_during_enabled``, ``judge_post_enabled``)
    #: from this per §3.4.1 — see :func:`derive_switches_from_mode`.
    default_execution_mode: ExecutionMode = ExecutionMode.NATIVE_REACT
    #: Tier 1 pre-llm_call auto-compact threshold. When the estimated
    #: ancestor-context footprint of a pending llm_call crosses
    #: ``compact_trigger_pct`` of the target model's context window,
    #: the engine inserts a compact WorkNode before the call. ``None``
    #: disables Tier 1 entirely for this ChatFlow.
    compact_trigger_pct: float | None = 0.7
    #: Target footprint for Tier 1 compact summaries, expressed as a
    #: fraction of the target model's context window. Fed to the
    #: compact worker as the ``target_tokens`` param. Must satisfy
    #: ``compact_trigger_pct + compact_target_pct <= 1.0`` (see
    #: the ChatFlow model_validator) so post-compact context is
    #: provably bounded by the model's window.
    compact_target_pct: float = 0.3
    #: Number of trailing messages kept verbatim on the downstream side
    #: of a compact. Smaller = more aggressive compaction, larger =
    #: more fidelity. Only consulted when
    #: ``compact_preserve_mode == "by_count"``.
    compact_keep_recent_count: int = 3
    #: Strategy for choosing the verbatim tail. ``by_count`` uses the N
    #: above (and lets the summary run uncapped); ``by_budget`` greedy-
    #: packs the tail into whatever is left of
    #: ``target_pct × context_window`` after the summary's tokens are
    #: subtracted. Applies to both tiers.
    compact_preserve_mode: CompactPreserveMode = "by_count"
    #: Stickiness counter-init for entries pulled back into context via
    #: ``get_node_context``. When a ChatNode/WorkNode is restored, it's
    #: recorded on the current ChatNode's ``sticky_restored`` map with
    #: a forget counter starting at this value. Each subsequent turn
    #: that doesn't re-touch the entry decrements the counter by 1; at
    #: 0 the entry drops out and falls back to the MemoryBoard-reference
    #: form. Larger = recalled content stays pinned longer. Independent
    #: of ``compact_preserve_mode`` (previously shared the same knob
    #: with the by_count tail length — decoupled in the compact-toggle
    #: work so by_budget mode no longer accidentally locks this too).
    recalled_context_sticky_turns: int = 3
    #: Optional model pin for the compact worker itself. Lets users
    #: route compactions to a cheap-and-fast model while keeping a
    #: strong model for the main turn. ``None`` falls back to the
    #: per-WorkNode ``model_override`` → turn model → chatflow default.
    compact_model: ProviderModelRef | None = None
    #: When True, a UI-driven auto-compact trigger (Tier 2) opens a
    #: confirmation dialog before running. The backend field exists
    #: so the preference travels with the ChatFlow; the dialog itself
    #: lives in the frontend.
    compact_require_confirmation: bool = True
    #: ChatFlow-layer auto-compact trigger (dual-track, independent of
    #: the WorkFlow Tier 1 trigger above). Evaluated at ChatNode spawn:
    #: if the prospective chain context (``entry_prompt_tokens``) crosses
    #: ``chatnode_compact_trigger_pct`` of the turn model's context
    #: window, the engine inserts a compact ChatNode *before* the new
    #: turn and forwards the turn into the compact node's pending_queue.
    #: ``None`` disables the ChatFlow-layer trigger. Reuses
    #: ``compact_keep_recent_count`` and ``compact_model``.
    chatnode_compact_trigger_pct: float | None = 0.6
    #: Target footprint for ChatNode-level compact summaries, as a
    #: fraction of the turn model's context window. Fed to the compact
    #: worker as ``target_tokens``.
    chatnode_compact_target_pct: float = 0.4
    sticky_notes: dict[str, StickyNote] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=utcnow)

    @model_validator(mode="before")
    @classmethod
    def _accept_legacy_default_model(cls, data: Any) -> Any:
        """Backwards-compat: accept the pre-MemoryBoard ``default_model``
        JSON key as an alias for ``draft_model``. Migration 0012 rewrites
        persisted payloads, but in-flight API calls and older test
        fixtures may still carry the old name; we translate on ingest so
        a mixed runtime (old code paths writing, new code reading) never
        loses the field. When both are present, ``draft_model`` wins —
        the new key is the authoritative one going forward.
        """
        if isinstance(data, dict):
            if "default_model" in data and "draft_model" not in data:
                data = {**data, "draft_model": data["default_model"]}
            # Tolerate both being present: drop the legacy so the
            # validator doesn't complain about an unknown key. We
            # deliberately keep this silent — logging would spam every
            # API hit during the migration window.
            if "default_model" in data and "draft_model" in data:
                data = {k: v for k, v in data.items() if k != "default_model"}
        return data

    @model_validator(mode="after")
    def _check_brief_model_context_window(self) -> "ChatFlow":
        """``brief_model``'s context window must be ≥ ``draft_model``'s.

        Reason: a flow-brief must fit the full upstream context of any
        draft node it summarizes — routing briefs to a smaller window
        would silently truncate. Lookup goes through the in-memory
        ``provider_context_cache``; if either model is unknown to the
        cache (lookup returns None) the validator passes silently so
        an unseeded test fixture or a fresh process doesn't error on
        every construction. The runtime cache gets populated by the
        API lifespan hook once a provider repository is available.
        """
        if self.brief_model is None or self.draft_model is None:
            return self
        try:
            from agentloom.engine.provider_context_cache import lookup
        except Exception:  # pragma: no cover — defensive for unusual import orders
            return self
        brief_cw = lookup(self.brief_model)
        draft_cw = lookup(self.draft_model)
        if brief_cw is None or draft_cw is None:
            return self
        if brief_cw < draft_cw:
            raise ValueError(
                "brief_model's context window must be >= draft_model's "
                f"(brief={brief_cw} tokens, draft={draft_cw} tokens)"
            )
        return self

    @model_validator(mode="after")
    def _check_compact_invariants(self) -> "ChatFlow":
        """Both compact tiers must satisfy ``trigger + target <= 1.0``.

        Proof sketch: at trigger time pre-compact context = trigger×max,
        and ``preserved + new_user`` is a subset of pre-compact so it's
        also ≤ trigger×max. After compact: summary + preserved + new_user
        ≤ (target + trigger)×max (the engine hard-caps summary at
        target×max). The constraint ``trigger + target ≤ 1.0`` therefore
        guarantees post-compact context ≤ max, preventing a second-turn
        blowup past the model's window.
        """
        if (
            self.compact_trigger_pct is not None
            and self.compact_trigger_pct + self.compact_target_pct > 1.0
        ):
            raise ValueError(
                "compact_trigger_pct + compact_target_pct must be <= 1.0 "
                f"(got {self.compact_trigger_pct} + {self.compact_target_pct} "
                f"= {self.compact_trigger_pct + self.compact_target_pct:.3f})"
            )
        if (
            self.chatnode_compact_trigger_pct is not None
            and self.chatnode_compact_trigger_pct
            + self.chatnode_compact_target_pct
            > 1.0
        ):
            raise ValueError(
                "chatnode_compact_trigger_pct + chatnode_compact_target_pct "
                "must be <= 1.0 "
                f"(got {self.chatnode_compact_trigger_pct} + "
                f"{self.chatnode_compact_target_pct} = "
                f"{self.chatnode_compact_trigger_pct + self.chatnode_compact_target_pct:.3f})"
            )
        return self

    @property
    def root_id(self) -> NodeId | None:
        """The single root id (§3.2 single-root decision).

        Returns the first entry of ``root_ids`` for forward-compat with
        legacy payloads that may technically have multiple roots; the
        invariant going forward is ``len(root_ids) <= 1`` on new data.
        """
        return self.root_ids[0] if self.root_ids else None

    def add_node(self, node: ChatFlowNode) -> ChatFlowNode:
        if node.id in self.nodes:
            raise ValueError(f"duplicate node id {node.id}")
        for p in node.parent_ids:
            if p not in self.nodes:
                raise ValueError(f"parent {p!r} not in chatflow")
        self.nodes[node.id] = node
        if not node.parent_ids:
            self.root_ids.append(node.id)
        return node

    def remove_node(self, node_id: NodeId) -> None:
        if node_id not in self.nodes:
            raise KeyError(node_id)
        for other in self.nodes.values():
            if node_id in other.parent_ids:
                raise NodeHasReferencesError(
                    f"node {node_id} still referenced by {other.id}"
                )
        del self.nodes[node_id]
        if node_id in self.root_ids:
            self.root_ids.remove(node_id)

    def children(self, node_id: NodeId) -> list[NodeId]:
        """Return immediate children of *node_id* (sorted by created_at)."""
        kids = [
            n for n in self.nodes.values() if node_id in n.parent_ids
        ]
        kids.sort(key=lambda n: (n.created_at, n.id))
        return [n.id for n in kids]

    def descendants(self, node_id: NodeId) -> set[NodeId]:
        """Return all transitive descendants of *node_id* (not including itself)."""
        result: set[NodeId] = set()
        stack = list(self.children(node_id))
        while stack:
            nid = stack.pop()
            if nid in result:
                continue
            result.add(nid)
            stack.extend(self.children(nid))
        return result

    def remove_subtree(self, node_id: NodeId) -> list[NodeId]:
        """Remove *node_id* and all its descendants. Returns the list of removed ids."""
        to_remove = self.descendants(node_id)
        to_remove.add(node_id)
        for rid in to_remove:
            if rid in self.nodes:
                del self.nodes[rid]
            if rid in self.root_ids:
                self.root_ids.remove(rid)
        return list(to_remove)

    def ancestors(self, node_id: NodeId) -> list[NodeId]:
        if node_id not in self.nodes:
            raise KeyError(node_id)
        seen: set[NodeId] = set()
        order: list[NodeId] = []

        def visit(nid: NodeId) -> None:
            if nid in seen:
                return
            seen.add(nid)
            for p in self.nodes[nid].parent_ids:
                visit(p)
            order.append(nid)

        for p in self.nodes[node_id].parent_ids:
            visit(p)
        return order

    def get(self, node_id: NodeId) -> ChatFlowNode:
        return self.nodes[node_id]


def make_chatflow(
    title: str | None = None,
    *,
    greeting: str | None = None,
) -> ChatFlow:
    """Create a ChatFlow pre-seeded with a greeting root.

    The greeting root has ``user_message=None`` and a frozen
    ``agent_response`` set to ``greeting`` (or :data:`DEFAULT_GREETING`).
    It exists so callers never see an "empty" chatflow — the first
    user turn always lands as a child of the greeting root, not as a
    free-floating bootstrap node. This also gives us a single place
    to hang future root-behavior features (opening prompts, preloaded
    tools, persona, ...).

    The root is marked ``SUCCEEDED`` so the scheduler's walk-down
    logic (which only consumes from succeeded leaves) treats it
    exactly like any other frozen turn.
    """
    chat = ChatFlow(title=title)
    now = utcnow()
    root = ChatFlowNode(
        user_message=None,
        agent_response=EditableText.by_agent(greeting or DEFAULT_GREETING),
        status=NodeStatus.SUCCEEDED,
        started_at=now,
        finished_at=now,
    )
    chat.add_node(root)
    return chat
