"""ChatFlow and ChatFlowNode — the outer conversation graph."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

from agentloom.schemas.common import (
    EditableText,
    NodeBase,
    NodeHasReferencesError,
    NodeId,
    NodeStatus,
    ProviderModelRef,
    generate_node_id,
    utcnow,
)
from agentloom.schemas.workflow import WorkFlow


#: Canned greeting written to a brand-new ChatFlow's root node. Static
#: for MVP; once root-behaviors land, this will be replaced by a mini
#: workflow the chat designer can edit (prompts, tools, etc.).
DEFAULT_GREETING = "Hi! I'm your assistant. Ask me anything."


PendingTurnSource = Literal["web", "discord", "feishu", "api", "test"]

#: What to do with a queued turn whose upstream node just failed.
#:
#: - ``discard`` (default): drop the turn, notify the channel. Used by
#:   every channel in Round A — failures are treated as conversation
#:   breakers, not transient glitches.
#: - ``continue``: ignore the upstream failure and try to run anyway.
#:   Reserved for future channels that want at-least-once semantics
#:   (e.g. a batch-ingest channel that retries each turn independently).
#:   The engine does *not* honor ``continue`` yet — the field is stored
#:   so the policy travels with the turn and the call-site decision
#:   stays in one place once the feature lands.
UpstreamFailurePolicy = Literal["discard", "continue"]


class PendingTurn(BaseModel):
    """A queued-but-not-yet-executed user turn attached to a ChatFlowNode.

    Lives on ``ChatFlowNode.pending_queue`` — see ADR-009 addendum: the
    pending_queue is ancillary state, not part of the node's frozen
    dialogue payload, so it can be mutated on a frozen node.

    The queue "walks" down the chain as each node transitions to
    succeeded: the head item becomes the user_message of a newly-created
    child, and the remaining tail is transferred to that child's own
    pending_queue. Whichever node currently holds the queue is the
    "live tip" of its chain.

    ``source`` captures which channel submitted the turn so the
    scheduler can apply channel-specific failure policies (e.g. discard
    vs. continue on upstream failure). ``source_metadata`` carries
    per-channel meta such as discord user id / thread id — opaque to
    the engine.
    """

    id: NodeId = Field(default_factory=generate_node_id)
    text: str
    source: PendingTurnSource = "web"
    source_metadata: dict[str, Any] = Field(default_factory=dict)
    on_upstream_failure: UpstreamFailurePolicy = "discard"
    created_at: datetime = Field(default_factory=utcnow)


class ChatFlowNode(NodeBase):
    """One user-turn + agent-turn pair, or the greeting root.

    Two shapes exist:
    - **Turn node**: ``user_message`` is set; ``agent_response`` is set
      once the inner workflow has run; ``workflow`` is the inner DAG
      that produced the response.
    - **Greeting root**: ``user_message`` is ``None``; ``agent_response``
      carries an opening line from the chat designer (static for MVP,
      will become a mini-workflow once root-behaviors land).

    Merge nodes have ``parent_ids`` with ≥2 entries; the ``user_message``
    is auto-generated by the ``merge`` system workflow in that case.

    ``pending_queue`` holds turns the user has submitted but that
    haven't begun executing yet — see :class:`PendingTurn`. It is the
    only field on a frozen node the repository layer allows to change.
    """

    user_message: EditableText | None = None
    agent_response: EditableText = Field(default_factory=EditableText)
    workflow: WorkFlow = Field(default_factory=WorkFlow)
    pending_queue: list[PendingTurn] = Field(default_factory=list)


class ChatFlow(BaseModel):
    id: NodeId = Field(default_factory=generate_node_id)
    title: str | None = None
    nodes: dict[NodeId, ChatFlowNode] = Field(default_factory=dict)
    root_ids: list[NodeId] = Field(default_factory=list)
    default_chat_model: ProviderModelRef | None = None
    default_work_model: ProviderModelRef | None = None

    def add_node(self, node: ChatFlowNode) -> ChatFlowNode:
        if node.id in self.nodes:
            raise ValueError(f"duplicate node id {node.id}")
        for p in node.parent_ids:
            if p not in self.nodes:
                raise ValueError(f"parent {p!r} not in chatflow")
        self.nodes[node.id] = node
        if not node.parent_ids:
            self.root_ids.append(node.id)
        return node

    def remove_node(self, node_id: NodeId) -> None:
        if node_id not in self.nodes:
            raise KeyError(node_id)
        for other in self.nodes.values():
            if node_id in other.parent_ids:
                raise NodeHasReferencesError(
                    f"node {node_id} still referenced by {other.id}"
                )
        del self.nodes[node_id]
        if node_id in self.root_ids:
            self.root_ids.remove(node_id)

    def ancestors(self, node_id: NodeId) -> list[NodeId]:
        if node_id not in self.nodes:
            raise KeyError(node_id)
        seen: set[NodeId] = set()
        order: list[NodeId] = []

        def visit(nid: NodeId) -> None:
            if nid in seen:
                return
            seen.add(nid)
            for p in self.nodes[nid].parent_ids:
                visit(p)
            order.append(nid)

        for p in self.nodes[node_id].parent_ids:
            visit(p)
        return order

    def get(self, node_id: NodeId) -> ChatFlowNode:
        return self.nodes[node_id]


def make_chatflow(
    title: str | None = None,
    *,
    greeting: str | None = None,
) -> ChatFlow:
    """Create a ChatFlow pre-seeded with a greeting root.

    The greeting root has ``user_message=None`` and a frozen
    ``agent_response`` set to ``greeting`` (or :data:`DEFAULT_GREETING`).
    It exists so callers never see an "empty" chatflow — the first
    user turn always lands as a child of the greeting root, not as a
    free-floating bootstrap node. This also gives us a single place
    to hang future root-behavior features (opening prompts, preloaded
    tools, persona, ...).

    The root is marked ``SUCCEEDED`` so the scheduler's walk-down
    logic (which only consumes from succeeded leaves) treats it
    exactly like any other frozen turn.
    """
    chat = ChatFlow(title=title)
    now = utcnow()
    root = ChatFlowNode(
        user_message=None,
        agent_response=EditableText.by_agent(greeting or DEFAULT_GREETING),
        status=NodeStatus.SUCCEEDED,
        started_at=now,
        finished_at=now,
    )
    chat.add_node(root)
    return chat
