"""ChatFlow and ChatFlowNode — the outer conversation graph."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

from agentloom.schemas.common import (
    EditableText,
    ExecutionMode,
    NodeBase,
    NodeHasReferencesError,
    NodeId,
    NodeStatus,
    ProviderModelRef,
    StickyNote,
    generate_node_id,
    utcnow,
)
from agentloom.schemas.workflow import WorkFlow


#: Canned greeting written to a brand-new ChatFlow's root node. Static
#: for MVP; once root-behaviors land, this will be replaced by a mini
#: workflow the chat designer can edit (prompts, tools, etc.).
DEFAULT_GREETING = "Hi! I'm your assistant. Ask me anything."


PendingTurnSource = Literal["web", "discord", "feishu", "api", "test"]

#: What to do with a queued turn whose upstream node just failed.
#:
#: - ``discard`` (default): drop the turn, notify the channel. Used by
#:   every channel in Round A — failures are treated as conversation
#:   breakers, not transient glitches.
#: - ``continue``: ignore the upstream failure and try to run anyway.
#:   Reserved for future channels that want at-least-once semantics
#:   (e.g. a batch-ingest channel that retries each turn independently).
#:   The engine does *not* honor ``continue`` yet — the field is stored
#:   so the policy travels with the turn and the call-site decision
#:   stays in one place once the feature lands.
UpstreamFailurePolicy = Literal["discard", "continue"]


class PendingTurn(BaseModel):
    """A queued-but-not-yet-executed user turn attached to a ChatFlowNode.

    Lives on ``ChatFlowNode.pending_queue`` — see ADR-009 addendum: the
    pending_queue is ancillary state, not part of the node's frozen
    dialogue payload, so it can be mutated on a frozen node.

    The queue "walks" down the chain as each node transitions to
    succeeded: the head item becomes the user_message of a newly-created
    child, and the remaining tail is transferred to that child's own
    pending_queue. Whichever node currently holds the queue is the
    "live tip" of its chain.

    ``source`` captures which channel submitted the turn so the
    scheduler can apply channel-specific failure policies (e.g. discard
    vs. continue on upstream failure). ``source_metadata`` carries
    per-channel meta such as discord user id / thread id — opaque to
    the engine.
    """

    id: NodeId = Field(default_factory=generate_node_id)
    text: str
    source: PendingTurnSource = "web"
    source_metadata: dict[str, Any] = Field(default_factory=dict)
    on_upstream_failure: UpstreamFailurePolicy = "discard"
    created_at: datetime = Field(default_factory=utcnow)
    #: Model the user picked in the composer when this turn was queued.
    #: ``None`` → the child inherits from its primary parent's
    #: ``resolved_model``. Travels with the PendingTurn so a queued turn
    #: keeps its model choice even as the tip advances down the chain.
    spawn_model: ProviderModelRef | None = None
    #: Per-kind composer overrides for this turn. ``None`` falls back
    #: through chatflow.default_judge_model / default_tool_call_model
    #: → spawn_model → default_model. Lets the user route a single turn's
    #: judges/tool-call follow-ups to a different model than the main
    #: turn without touching ChatFlow defaults.
    judge_spawn_model: ProviderModelRef | None = None
    tool_call_spawn_model: ProviderModelRef | None = None


class ChatFlowNode(NodeBase):
    """One user-turn + agent-turn pair, or the greeting root.

    Two shapes exist:
    - **Turn node**: ``user_message`` is set; ``agent_response`` is set
      once the inner workflow has run; ``workflow`` is the inner DAG
      that produced the response.
    - **Greeting root**: ``user_message`` is ``None``; ``agent_response``
      carries an opening line from the chat designer (static for MVP,
      will become a mini-workflow once root-behaviors land).

    Merge nodes have ``parent_ids`` with ≥2 entries; the ``user_message``
    is auto-generated by the ``merge`` system workflow in that case.

    ``pending_queue`` holds turns the user has submitted but that
    haven't begun executing yet — see :class:`PendingTurn`. It is the
    only field on a frozen node the repository layer allows to change.
    """

    user_message: EditableText | None = None
    agent_response: EditableText = Field(default_factory=EditableText)
    workflow: WorkFlow = Field(default_factory=WorkFlow)
    pending_queue: list[PendingTurn] = Field(default_factory=list)


class ChatFlow(BaseModel):
    id: NodeId = Field(default_factory=generate_node_id)
    title: str | None = None
    description: str | None = None
    tags: list[str] = Field(default_factory=list)
    nodes: dict[NodeId, ChatFlowNode] = Field(default_factory=dict)
    root_ids: list[NodeId] = Field(default_factory=list)
    default_model: ProviderModelRef | None = None
    #: Per-call-type overrides of ``default_model``. When set, judge
    #: calls (pre/during/post) use ``default_judge_model``; tool-call
    #: follow-up LLM calls use ``default_tool_call_model``. Falls back
    #: to ``default_model`` when ``None``. Lets a chatflow run a cheap
    #: model for verification/tool-routing while keeping a strong model
    #: for the main LLM step.
    default_judge_model: ProviderModelRef | None = None
    default_tool_call_model: ProviderModelRef | None = None
    #: ReAct inner-loop cap shared by every WorkFlow in this ChatFlow.
    #: ``None`` means unlimited. Per-WorkFlow and per-WorkNode overrides
    #: are planned. See §5.4 FR-EX-6.
    tool_loop_budget: int | None = 12
    #: Auto-mode halt cap: total ``judge_during.verdict == "revise"`` tolerated
    #: per WorkFlow run before the engine pauses at ``waiting_for_user``.
    #: Per-WorkNode override allowed; ``None`` = unlimited. See §5.3 FR-PL-7.
    auto_mode_revise_budget: int | None = 3
    #: Hard cap on planner↔planner_judge / worker↔worker_judge debate
    #: rounds before the engine forces convergence (routes through
    #: judge_post). Applied to every new turn's inner WorkFlow. See §3.4.5.
    debate_round_budget: int = 3
    #: Hard cap on judge_post retry rounds. When a judge_post returns
    #: ``verdict=retry`` with ``redo_targets``, the engine re-spawns
    #: those subtasks and re-aggregates — up to this many rounds total
    #: (round 1 is the initial judgement). ``-1`` = unlimited. Applied
    #: to every new turn's inner WorkFlow.
    judge_retry_budget: int = 3
    #: Ground-ratio fuse — halts a WorkFlow (or sub_agent_delegation)
    #: whose planner is spinning without ever reaching a real tool_call.
    #: ``min_ground_ratio`` is the minimum fraction of completed leaf
    #: nodes (llm_call + tool_call + judge_call, excluding
    #: sub_agent_delegation containers) that must be ``tool_call`` before
    #: the engine halts the layer. ``None`` disables the check entirely.
    #: ``ground_ratio_grace_nodes`` is the number of completed leaves
    #: required before the fuse arms — keeps a healthy run's first few
    #: planner/judge steps from tripping it. Each recursive engine level
    #: evaluates its own local ratio independently; overall runaway is
    #: still bounded because every level applies the fuse. See §5.4
    #: (planner-grounding fuse).
    min_ground_ratio: float | None = 0.05
    ground_ratio_grace_nodes: int = 20
    #: Per-ChatFlow tool denylist. Tool names listed here are hidden
    #: from every LLM call inside this chatflow's WorkFlows AND refused
    #: at execute-time if the model hallucinates them. Covers both
    #: built-in tools (``Bash``, ``Read``, etc.) and MCP tools
    #: (``mcp__<server>__<tool>``). An empty list means "no extra
    #: filter" — every globally-registered tool is visible.
    #:
    #: New chatflows pre-populate this from the workspace tool settings
    #: (every tool whose global state is ``available`` lands in here so
    #: it stays unchecked by default; ``default_allow`` tools are NOT
    #: pre-listed and remain checked). See M7.5 step 2/3.
    disabled_tool_names: list[str] = Field(default_factory=list)
    #: Execution mode applied to every new turn's inner WorkFlow. The
    #: ChatFlowEngine derives the four switch defaults (``plan_enabled``,
    #: ``judge_pre_enabled``, ``judge_during_enabled``, ``judge_post_enabled``)
    #: from this per §3.4.1 — see :func:`derive_switches_from_mode`.
    default_execution_mode: ExecutionMode = ExecutionMode.DIRECT
    sticky_notes: dict[str, StickyNote] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=utcnow)

    @property
    def root_id(self) -> NodeId | None:
        """The single root id (§3.2 single-root decision).

        Returns the first entry of ``root_ids`` for forward-compat with
        legacy payloads that may technically have multiple roots; the
        invariant going forward is ``len(root_ids) <= 1`` on new data.
        """
        return self.root_ids[0] if self.root_ids else None

    def add_node(self, node: ChatFlowNode) -> ChatFlowNode:
        if node.id in self.nodes:
            raise ValueError(f"duplicate node id {node.id}")
        for p in node.parent_ids:
            if p not in self.nodes:
                raise ValueError(f"parent {p!r} not in chatflow")
        self.nodes[node.id] = node
        if not node.parent_ids:
            self.root_ids.append(node.id)
        return node

    def remove_node(self, node_id: NodeId) -> None:
        if node_id not in self.nodes:
            raise KeyError(node_id)
        for other in self.nodes.values():
            if node_id in other.parent_ids:
                raise NodeHasReferencesError(
                    f"node {node_id} still referenced by {other.id}"
                )
        del self.nodes[node_id]
        if node_id in self.root_ids:
            self.root_ids.remove(node_id)

    def children(self, node_id: NodeId) -> list[NodeId]:
        """Return immediate children of *node_id* (sorted by created_at)."""
        kids = [
            n for n in self.nodes.values() if node_id in n.parent_ids
        ]
        kids.sort(key=lambda n: (n.created_at, n.id))
        return [n.id for n in kids]

    def descendants(self, node_id: NodeId) -> set[NodeId]:
        """Return all transitive descendants of *node_id* (not including itself)."""
        result: set[NodeId] = set()
        stack = list(self.children(node_id))
        while stack:
            nid = stack.pop()
            if nid in result:
                continue
            result.add(nid)
            stack.extend(self.children(nid))
        return result

    def remove_subtree(self, node_id: NodeId) -> list[NodeId]:
        """Remove *node_id* and all its descendants. Returns the list of removed ids."""
        to_remove = self.descendants(node_id)
        to_remove.add(node_id)
        for rid in to_remove:
            if rid in self.nodes:
                del self.nodes[rid]
            if rid in self.root_ids:
                self.root_ids.remove(rid)
        return list(to_remove)

    def ancestors(self, node_id: NodeId) -> list[NodeId]:
        if node_id not in self.nodes:
            raise KeyError(node_id)
        seen: set[NodeId] = set()
        order: list[NodeId] = []

        def visit(nid: NodeId) -> None:
            if nid in seen:
                return
            seen.add(nid)
            for p in self.nodes[nid].parent_ids:
                visit(p)
            order.append(nid)

        for p in self.nodes[node_id].parent_ids:
            visit(p)
        return order

    def get(self, node_id: NodeId) -> ChatFlowNode:
        return self.nodes[node_id]


def make_chatflow(
    title: str | None = None,
    *,
    greeting: str | None = None,
) -> ChatFlow:
    """Create a ChatFlow pre-seeded with a greeting root.

    The greeting root has ``user_message=None`` and a frozen
    ``agent_response`` set to ``greeting`` (or :data:`DEFAULT_GREETING`).
    It exists so callers never see an "empty" chatflow — the first
    user turn always lands as a child of the greeting root, not as a
    free-floating bootstrap node. This also gives us a single place
    to hang future root-behavior features (opening prompts, preloaded
    tools, persona, ...).

    The root is marked ``SUCCEEDED`` so the scheduler's walk-down
    logic (which only consumes from succeeded leaves) treats it
    exactly like any other frozen turn.
    """
    chat = ChatFlow(title=title)
    now = utcnow()
    root = ChatFlowNode(
        user_message=None,
        agent_response=EditableText.by_agent(greeting or DEFAULT_GREETING),
        status=NodeStatus.SUCCEEDED,
        started_at=now,
        finished_at=now,
    )
    chat.add_node(root)
    return chat
